# Neural Network from Scratch (NumPy)

This project implements a neural network from scratch using NumPy to solve the XOR problem.

Approach :
- Input layer (2 neurons)
- Hidden layer (4 neurons)
- Output layer (1 neuron)
- Sigmoid activation
- Backpropagation for learning

In [1]:
import numpy as np

In [2]:
X = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
])

y = np.array([[0, 1, 1, 0]]).T

In [3]:
np.random.seed(1)

weights = 2 * np.random.random((3, 1)) - 1
print(weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [6]:
for i in range(10000):

    input_layer = X

    outputs = sigmoid(np.dot(input_layer, weights))

    error = y - outputs

    adjustments = error * sigmoid_derivative(outputs)

    weights += np.dot(input_layer.T, adjustments)

In [7]:
print("Output after training:")
print(outputs)

Output after training:
[[0.00966449]
 [0.99211957]
 [0.99358898]
 [0.00786506]]


In [8]:
import numpy as np

X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([[0],[1],[1],[0]])

In [9]:
np.random.seed(1)

# input → hidden
weights1 = 2 * np.random.random((2, 4)) - 1

# hidden → output
weights2 = 2 * np.random.random((4, 1)) - 1

In [10]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [11]:
for i in range(10000):

    # Forward propagation
    layer0 = X
    layer1 = sigmoid(np.dot(layer0, weights1))
    layer2 = sigmoid(np.dot(layer1, weights2))

    # Error
    error = y - layer2

    # Backpropagation
    d_layer2 = error * sigmoid_derivative(layer2)
    d_layer1 = d_layer2.dot(weights2.T) * sigmoid_derivative(layer1)

    # Update weights
    weights2 += layer1.T.dot(d_layer2)
    weights1 += layer0.T.dot(d_layer1)

The model successfully learns the XOR function, producing outputs close to expected values.

In [12]:
print("Output after training:")
print(layer2)

Output after training:
[[0.02152435]
 [0.98341551]
 [0.98034016]
 [0.01804214]]
